/**:
  ros__parameters:
    serial_port:
      name: "/dev/ttyUSB0"

    BNO055:
      acc_factor: 100.0
      mag_factor: 16000000.0
      gyro_factor: 900.0
      grav_factor: 100.0
      data_frequency: 100.0 # max 62.5 hz
      make_calibration: false
      set_offset: true
      acc_offset: [65463, 50, 65406]
      mag_offset: [65493, 84, 65460]
      gyro_offset: [65534, 2, 0]
